# Numpy: Package for Multi-Dimensional Array

In [1]:
import numpy as np # alias name given to numpy as np 
sample_list = [1,2,4] # 1D Array
sample_list0 = np.array(sample_list) # providing list after creating
print(sample_list0)
type(sample_list0)

[1 2 4]


numpy.ndarray

In [2]:
sample_list1 = np.array([2,6,9]) # directly adding list w/o creating first
print(sample_list1)

[2 6 9]


In [3]:
from numpy import * # importing numpy completely w/o alias name
sample_list = [1,2,4]
sample_list0 = np.array(sample_list) 
print(sample_list0)
type(sample_list0) 
'''this way task is simplified as well as complicated coz you don't have to write alias name again and again but it became hard
to differentiate and understand for other user '''

[1 2 4]


"this way task is simplified as well as complicated coz you don't have to write alias name again and again but it became hard\nto differentiate and understand for other user "

In [4]:
import numpy as np # 2-D Array
sample_list_ = [[1,2,3],[4,5,6],[9,8,7]]
arr = np.array(sample_list_)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [5]:
np.arange(2,60,10) #start from no. 2, ends at 60 excluding 60 itself and with a stepsize of 10

array([ 2, 12, 22, 32, 42, 52])

In [6]:
np.arange(10) #in such case start and stepsize are considered as 0 and given value is taken as end value which is excluded

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(10) # 0 are of FLoat DataType bydefault 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((2,3)) # 2 rol and 3 col array of 0's

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros(6,int) # array of 6 0's as int DataType

array([0, 0, 0, 0, 0, 0])

In [10]:
np.ones(3) # bydefault Float DataType array

array([1., 1., 1.])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones((2,4),int) # int DataType 

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
np.linspace(0,2,5) # start from 0, end at 2 and have 5 values Linearly-Spaced b/w 0 and 2 inclusively

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
np.eye(10) #identity matrix of 10*10

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(3,5) # random float number between 0 and 1 excluding them, with 3 rows and 5 columns

array([[0.25195843, 0.80167198, 0.27038629, 0.86056919, 0.80031951],
       [0.94750318, 0.26885061, 0.21128187, 0.65567593, 0.15369996],
       [0.12139805, 0.93249379, 0.78077978, 0.65237713, 0.43503343]])

In [16]:
np.random.randn(1,5) # random float both +ve and +ve with 1 rows and 5 columns

array([[ 2.15286853,  0.16285834, -0.03549749, -2.49041902,  1.616921  ]])

In [17]:
np.random.randint(2,100) # random integer between 2 and 100

28

In [18]:
np.random.randint(2,100,20)# 20 random integer between 2 and 100

array([66,  2, 24, 59, 94, 72, 13, 94, 82, 22, 47, 94, 12, 89, 76, 83,  5,
       16, 37, 64])

In [19]:
arr = np.arange(30) # guess the output
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
arr1 = np.random.randint(0,100,20) # guess the output
arr1

array([14,  5, 24, 52,  2, 80, 54,  0, 32, 16, 74, 83, 50, 33, 22, 15, 52,
       75, 26,  1])

In [21]:
arr.reshape(10,3) # reshape the array into desired no. of rows and columns like here arr named array into 10 row and 3 col

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [22]:
arr.reshape(2,3) # can't reshape this time coz 2 rows and 3 cols can only have 6 elements but in arr named array there are 30 

ValueError: cannot reshape array of size 30 into shape (2,3)

In [23]:
arr.max() # gives maximum value in array as output 

29

In [24]:
arr1.argmax() # gives index value of maximum value in array as output

11

In [25]:
samp = np.random.randint(20,56,20)
samp1 = samp.reshape(4,5)
print(samp1)

[[32 28 37 37 29]
 [54 54 48 21 49]
 [36 40 50 20 33]
 [47 32 20 51 24]]


In [26]:
samp1.T # .T function is used to create Transpose

array([[32, 54, 36, 47],
       [28, 54, 40, 32],
       [37, 48, 50, 20],
       [37, 21, 20, 51],
       [29, 49, 33, 24]])

In [27]:
samp1[0][0] # 0 == 0th row (i.e., first row in indexing counting start from 0) & 0 == 1st column value from 0th row 
# retrieve value from array 1st number represent row and 2nd column no.

32

In [28]:
sample_arr1 = np.arange(10,21)
sample_arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
sample_arr1[0] # retreiving element from array using index no.

10

In [30]:
sample_arr1[2:5] # retreiving element b/w 2 to 5 exclusive of index no. 5

array([12, 13, 14])

In [31]:
sample_arr1[4:6]= 1
sample_arr1

array([10, 11, 12, 13,  1,  1, 16, 17, 18, 19, 20])

In [32]:
sample_arr1[:6]

array([10, 11, 12, 13,  1,  1])

In [33]:
sample_arr1[0:]

array([10, 11, 12, 13,  1,  1, 16, 17, 18, 19, 20])

In [34]:
sample_arr1[:] = 1001
sample_arr1[:]

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two Dimensional Array

In [35]:
import numpy as np
samp_1 = np.array([[1,2,3],[4,5,6],[9,8,7]])
samp_1

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [36]:
samp_1[1,2] # 1 represent row with index no. 1 and 2 represent column with index no. 2 in given row (index no. start from 0)
samp_1[1][2] # both are same

6

In [37]:
samp_1[2,:] # complete row with index no. 2
samp_1[2] #both are same

array([9, 8, 7])

In [38]:
samp_1[:,(1,2)]  # value of column's with index no. 1 & 2 from all rows

array([[2, 3],
       [5, 6],
       [8, 7]])

### Selection Techniques

In [39]:
samp_arr = np.arange(1,20)
samp_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [40]:
samp_arr + samp_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [41]:
np.exp(samp_arr) #exponential 

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [42]:
np.sqrt(samp_arr) #square root

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [43]:
np.log(samp_arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [44]:
np.max(samp_arr)

19

In [45]:
np.min(samp_arr)

1

In [46]:
np.argmax(samp_arr)

18

In [47]:
np.argmin(samp_arr)

0

In [48]:
np.square(samp_arr)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [49]:
np.std(samp_arr) # std --> Standard Deviation

5.477225575051661

In [50]:
np.var(samp_arr) # var --> Variance

30.0

In [51]:
np.mean(samp_arr)

10.0

In [52]:
arr0 = np.random.randn(3,4)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
np.round(arr0,decimals=2) # rounding of to two digits

array([[-0.46, -0.67, -1.85,  0.12],
       [ 0.76,  0.44,  0.02,  1.2 ],
       [ 0.65,  0.11,  0.3 , -0.18]])

In [ ]:
sport = ["cricket","football","run","cricket"]
np.unique(sport) # removes any duplicate present 